### ISSUE TITLE
Is there a new release coming?

### ISSUE THREAD

**Issue by dunmatt** [adnanademovic/rosrust#104]
I'm using 0.7.1 since that's what's in crates.io, but I'm running into some unwrapping Error crashes under some circumstances when Python nodes are publishing to me.  Starting to debug that I noticed how old 0.7.1 is.  Is there a new release coming at some point?  If so, will the new release have working docs on docs.rs?

Is there something specific blocking a new version?

**Comment by adnanademovic** [comment]
I'd say it's inertia.

I'll bump a release right now. Since it's in the 0.x stage, it doesn't matter how many unrelated changes are bundled together.
