### ISSUE TITLE
test publisher_to_inline_subscriber fails

### ISSUE THREAD

**Issue by kjeremy** [adnanademovic/rosrust#118]
`cargo test` reports

> Running target/debug/deps/publisher_to_inline_subscriber-a95d557a5178cf8d
> 
> running 1 test
> test publisher_to_inline_subscriber ... FAILED
> 
> failures:
> 
> ---- publisher_to_inline_subscriber stdout ----
> Running roscore on port: 11701
> Received message at level 2: hello world
> thread 'publisher_to_inline_subscriber' panicked at 'assertion failed: `(left == right)`
>   left: `2`,
>  right: `1`', rosrust/tests/publisher_to_inline_subscriber.rs:30:5

**Comment by adnanademovic** [comment]
I've noticed that issue on Travis, but cannot replicate it locally on any machine.

Did you manage to replicate it?
