### ISSUE TITLE
Can't subscribe to std_msgs/String

### ISSUE THREAD

**Issue by Vourhey** [adnanademovic/rosrust#141]
I don't know if it's related to rosrust specifically but our team uses rosrust to handle ROS topics.

At the moment it's possible to send messages from rust and catch it via rostopic, but publishing from rostopic and catching in rust is not possible.

Here's the [issue](https://github.com/airalab/robonomics/issues/72) in our package. And here's the line where all the magic must happen [link](https://github.com/airalab/robonomics/blob/master/robonomics/io/src/source/virt.rs#L125)

The package is located here https://github.com/airalab/robonomics/blob/master/substrate-ros/

**Comment by adnanademovic** [comment]
This might be totally unrelated, but you're not doing anything with the `Result` returned by `try_init_with_options`. You might be even getting an issue there.

I also recommend setting up some logger that connects to the `log` library. `rosrust` might be giving you warnings about interactions with other nodes, but you're not seeing them. A simple example is `env_logger`.
