### ISSUE TITLE
Ros Node is not cleaned up after exiting.

### ISSUE THREAD

**Issue by hojjatabdollahi** [adnanademovic/rosrust#158]
I have been testing the code using the examples provided.
After I create a node I can see the node using the `rosnode list` command.
If I stop the node: either using `ctrl+c` or `rosnode kill /talker`, the node still shows up in `rosnode list`.
The only way to get rid of it is to run `rosnode cleanup`. 
This behavior happens in cpp if you abruptly stop a node and the node doesn't have enough time to cleanup.
I tried to add `rosrust::shutdown()` to the code in the examples, but it did not fix the issue.
Am I doing something wrong? Is this known/intended?

**Comment by adnanademovic** [comment]
Automatic cleanup happens now if:
* `rosrust::is_ok() == false`
* `rosrust::spin()` terminates
* `rosrust::shutdown()` is called

If you're not using any of the mechanisms, you can easily use [the defer crate](https://docs.rs/defer/latest/defer/) to defer a `rosrust::shutdown()` call for the end of `main`.
