### ISSUE TITLE
Derive Serde's Serialize and Deserialize for the generated message structs

### ISSUE THREAD

**Issue by glennib** [adnanademovic/rosrust#178]
I have a use case where I need to serialize messages received on a ROS topic into a binary format.
I figured I could use Serde on the rosrust_msg::* types to achieve this.
It seems like the generated message types don't implement Serialize and Deserialize.
Would it be possible to add those derive macros to the generated message types?
I tried to do it, but I'm not sure where to append the `use serde::{Serialize, Deserialize};` line in the `rosrust` code.
If someone can point me in the right direction I'll make a PR.

**Comment by adnanademovic** [comment]
I've explained in #137 that the new dynamic data format can be used to work with serde.

There were PRs before, you can read the whole discussion in #137 about why none were merged.
