### ISSUE TITLE
Upgrade nix to 0.25.1?

### ISSUE THREAD

**Issue by rtzoeller** [adnanademovic/rosrust#180]
Would it be possible to upgrade `rosrust` to use a newer version of the `nix` crate, such as `0.25.1`? I believe that is the latest version which is compatible with rosrust's MSRV.

Admittedly this is a selfish request - I am a co-maintainer for the `nix` crate. We are in the process of backporting some bug fixes to earlier versions, and 0.22 is right on the edge of what we'd consider backporting to (it predates a significant amount of CI and code improvements). `rosrust` is one of the major crates still using `nix` 0.22, so I thought I'd reach out.

I'd be happy to attempt this myself, however I run Fedora which is nontrivial to get ROS configured on (at least from what I recall from a few years ago).

**Comment by adnanademovic** [comment]
Thanks for the heads up.

It will be no problem to do. AFAIK (I'll double check) it's only used to clean up spawned processes in a couple integration tests. I'll make a note of it, but this is not a pressing issue for this crate.
