### ISSUE TITLE
rust analyzer not showing completion for custom messages but shows it for "built-in" messages like std_msgs/Header

### ISSUE THREAD

**Issue by noufelez** [adnanademovic/rosrust#188]
Hi,

At our company, we're considering using rosrust for message generation and ser-deserialisation of messages in order to interop with a large codebase of c++ code.

Message generation works great, for example I could  generate an EnergySpeed message form a .msg file. But, when hovering over it or ctrl+clicking into it I don't get anything. But when I do it for Header (which is a ros builtin type) I get this 
![image](https://user-images.githubusercontent.com/126268712/228267743-4062b21e-39d4-4a8f-8da7-28381117f8e6.png)
and I can click on it which takes me to a lib.rs file located in the rosrust_msg crate which contains this code:

`include!(concat!(env!("OUT_DIR"), "/", "messages.rs"));`

Is this somehow a limitation of rust-analyzer or a way with which rosrust is currently designed ? @adnanademovic 

Thank you for the amazing work!

**Comment by adnanademovic** [comment]
It might be a Rust Analyzer limitation. It might not be having a good time with finding or traversing to generated files within the `target` directory.

If it's any consolation, generating the documentation via `cargo doc --open` will give you documentation for all messages generated within `rosrust_msg`.

**Comment by noufelez** [comment]
Thanks for your response! :)

**Comment by SerenaLynas** [comment]
The hints work for me now. I think it may be related to [rust analyzer issue #16109](https://github.com/rust-lang/rust-analyzer/issues/16109) -- not sure.

If it's not working, make sure you have your ENV variables set up for message paths. You can see the RA logs in the "Output" pane of VSCode. If the crate fails to compile, RA won't try to compile it again, so you need to reload the RA language server. Then you should get hints.
