### ISSUE TITLE
pub sub not works in `/use_sim_time` `true` and `/clock` is published

### ISSUE THREAD

**Issue by OTL** [adnanademovic/rosrust#36]
pub sub example does not work when

* `/use_sim_time` param is true
* `/clock` is published correctly

## How to reproduce this problem

```
roscore
rosparam set /use_sim_time true
rostopic pub -s -r 1000 /clock rosgraph_msgs/Clock 'now'
./target/debug/publisher
./target/debug/subscriber
```

## `roscpp_tutorials` works fine in this situation.

```
roscore
rosparam set /use_sim_time true
rostopic pub -s -r 1000 /clock rosgraph_msgs/Clock 'now'
rosrun roscpp_tutorials talker
rosrun roscpp_tutorials listener
```

**Comment by OTL** [comment]
FYI: What actually I want to do is,

publish `control_msgs/FollowJointTrajectoryActionGoal.msg` from `rosrust` to gazebo simulator.

I used 

```
rostopic pub -s -r 1000 /clock rosgraph_msgs/Clock 'now'
```

instead of

```
roslaunch ur_gazebo ur5.launch
```

**Comment by adnanademovic** [comment]
This should also be fixed now

**Comment by adnanademovic** [comment]
Deployed in 0.6.3
