### ISSUE TITLE
Publisher type is not visible from outside crate

### ISSUE THREAD

**Issue by astraw** [adnanademovic/rosrust#42]
I cannot store a `Publisher` in a field in a struct because the type definition of `Publisher` is not visible outside the crate.

This can be easily fixed by making the `api` module public in `src/lib.rs`, but this seems like something you may have explicitly avoided.

**Comment by adnanademovic** [comment]
There is no reason to keep it private, so I switched it in master.

Good point, I broke that while switching to the singleton design.
