### ISSUE TITLE
Subscriber panics when malformed message comes in

### ISSUE THREAD

**Issue by ThijsRay** [adnanademovic/rosrust#66]
When malformed message is received by a subscriber, the subscriber panics with the following message:
`thread '<unnamed>' panicked at 'called 'Result::unwrap()' on an 'Err' value: Error(Msg("Failed to run the HTTP request within hyper."), State { next_error: Some(Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), backtrace: Some(stack backtrace: ...`

How to reproduce:
Use `rostopic` to publish an empty message to a topic, e.g. `rostopic pub /topicname std_msgs/Float32`

Rust backtrace shows that the following lines cause a panic
https://github.com/adnanademovic/rosrust/blob/7baf922506943cda24655216f4ed29e3c5736dba/rosrust/src/api/slave/subscriptions.rs#L98-L106

**Comment by adnanademovic** [comment]
This should be fixed on the master branch now.
