### ISSUE TITLE
Make error handling more sensible

### ISSUE THREAD

**Issue by adnanademovic** [adnanademovic/rosrust#9]
Most of the error messages are just tacked on there, since the focus was getting functionality out there.

Now that functionality is there, the next step is being more clear what's going on when errors happen.

This includes getting rid of .unwrap() calls that are placed to kill a thread when we're done with it, since they are making noise on stderr.

**Comment by cwoodall** [comment]
Have you seen the [error_chain](https://crates.io/crates/error-chain) crate.  Sends like a reasonable way of handling errors by automating a lot of the boilerplate.

**Comment by adnanademovic** [comment]
OMG this is exactly what I was doing with needlessly complicated enums. This could work out perfectly if it's what I think it is. Thanks!

**Comment by cwoodall** [comment]
I believe it was made to make the enums your making easier to make! Seems to have been developed by the rustup team

**Comment by adnanademovic** [comment]
Yeah, this is perfect for this project, since most of the errors that can arise are unexpected critical errors that should be propagated to the library user, so having something like this really does the job. I'll use this ASAP.
