### ISSUE TITLE
published messages not seen by some tools

### ISSUE THREAD

**Issue by 6xzo** [adnanademovic/rosrust#92]
A very simple publisher, such as the chatter example in the readme, publishes messages that don't seem to be seen by all tools. `rostopic echo /chatter` sees them, but `rostopic hz /chatter` and `rosbag record /chatter` do not. I noticed this while investigating that a LabView node also does not observe the messages. Publishing the same with `rostopic pub` or a Python publisher and all tools observe the messages. Tried with Ubuntu 16 Mate/kinetic on a raspberry Pi, Ubuntu 18 Mate/melodic on x64, and even with RosOnWindows/melodic, same result everywhere.

**Comment by adnanademovic** [comment]
Turns out it's tools that upon requesting a topic request a wildcard message type, instead of a fixed message type.

**Comment by adnanademovic** [comment]
The `wip` branch should have that fixed now.

**Comment by 6xzo** [comment]
Thank you. I will test it on my systems.
